import type { Adr, Engagement, Project, Release, RepoState } from "../types.js";

export interface MonthlyReviewInput {
  period: string;        // "YYYY-MM"
  generatedAt: string;   // ISO timestamp
  projects: Project[];
  releases: Release[];
  decisions: Adr[];
  engagement: Engagement[];
  state: RepoState;
}

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

function monthLabel(period: string): string {
  const [y, m] = period.split("-");
  const idx = Number(m) - 1;
  return `${MONTHS[idx] ?? m} ${y}`;
}

function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map(cell).join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

function list(items: string[], empty: string): string {
  return items.length ? items.map((i) => `- ${i}`).join("\n") : empty;
}

export function buildMonthlyReview(input: MonthlyReviewInput): string {
  const { period, generatedAt } = input;
  const label = monthLabel(period);
  const inPeriod = <T extends { date: string }>(xs: T[]) => xs.filter((x) => x.date.startsWith(period));

  const releases = inPeriod(input.releases).sort((a, b) => b.date.localeCompare(a.date));
  const decisions = inPeriod(input.decisions).sort((a, b) => b.date.localeCompare(a.date));
  const engagement = [...input.engagement].sort((a, b) => b.contributions - a.contributions);

  const out: string[] = [];
  out.push(`# Monthly Review — ${label}`);
  out.push("");
  out.push(`> Generated by **pulse** at ${generatedAt}. Derived from the repo — do not edit by hand.`);
  out.push("");

  out.push("## Portfolio");
  out.push(table(
    ["Project", "Status", "DRI", "Version", "Current focus", "Next gate"],
    input.projects.map((p) => [p.name, p.status, p.dri, p.version || "—", p.currentFocus, p.nextGate]),
  ));
  out.push("");

  out.push(`## Shipped in ${label}`);
  out.push(releases.length
    ? table(["Version", "Project", "Date", "Summary"], releases.map((r) => [r.version, r.project, r.date, r.summary]))
    : "_No releases this month._");
  out.push("");

  out.push(`## Decisions in ${label}`);
  out.push(decisions.length
    ? table(["ADR", "Title", "Status", "Date"], decisions.map((d) => [d.adr, d.title, d.status, d.date]))
    : "_No decisions this month._");
  out.push("");

  out.push("## Engagement");
  out.push(table(
    ["Member", "Contributions", "Kudos", "Status streak", "Events attended"],
    engagement.map((e) => [e.name, String(e.contributions), String(e.kudos), String(e.statusStreak), String(e.eventsAttended)]),
  ));
  out.push("");

  out.push("## Drivers");
  out.push(list(input.state.drivers.map((d) => `**${d.name}** (${d.role}) — ${d.detail}`), "_None recorded._"));
  out.push("");

  out.push("## Hot now");
  out.push(list(input.state.hotNow, "_Nothing flagged._"));
  out.push("");

  out.push("## Blockers");
  out.push(list(input.state.blockers, "_None._"));
  out.push("");

  return out.join("\n");
}
