function isoDay(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export interface RenderInput {
  date: Date;
  llmOutput: string;
  itemCount: number;
}

export function renderDigest(input: RenderInput): string {
  const day = isoDay(input.date);
  if (input.itemCount === 0) {
    return `# 🧠 Daily Digest — ${day}

A quiet day in News & Signals — no notable items.

_Generated by GBrain via Vercel AI Gateway._
`;
  }
  return `# 🧠 Daily Digest — ${day}

Covering ${input.itemCount} items from News & Signals in the last 24h.

${input.llmOutput.trim()}

_Generated by GBrain via Vercel AI Gateway. Reply with #skip to exclude a message from future digests._
`;
}
