import { describe, it, expect } from "vitest";
import { renderDigest } from "../../src/digest/render";

describe("renderDigest", () => {
  it("wraps LLM output in header + footer", () => {
    const md = renderDigest({
      date: new Date("2026-04-24T09:00:00Z"),
      llmOutput: "- **Thing happened** — https://x.com/foo — why it matters: X",
      itemCount: 3
    });
    expect(md).toMatch(/# 🧠 Daily Digest — 2026-04-24/);
    expect(md).toMatch(/Covering 3 items/);
    expect(md).toMatch(/- \*\*Thing happened\*\*/);
    expect(md).toMatch(/_Generated by GBrain/);
  });

  it("renders an empty-day message when itemCount is 0", () => {
    const md = renderDigest({
      date: new Date("2026-04-24T09:00:00Z"),
      llmOutput: "",
      itemCount: 0
    });
    expect(md).toMatch(/quiet day/i);
  });
});
